-- Manually derived DDL based on entity definitions

-- Org Table
CREATE TABLE orgs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip VARCHAR(255),
    contact_person VARCHAR(255),
    contact_phone VARCHAR(255),
    status VARCHAR(255)
);

-- User Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    status VARCHAR(255),
    org_id BIGINT,
    available_credit DECIMAL(19, 2),
    FOREIGN KEY (org_id) REFERENCES orgs(id)
);

-- Recognition Table
CREATE TABLE recognitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT,
    recognizer_user_id BIGINT,
    gifted_amount DECIMAL(19, 2),
    gifted_date TIMESTAMP,
    message VARCHAR(255),
    FOREIGN KEY (recipient_user_id) REFERENCES users(id),
    FOREIGN KEY (recognizer_user_id) REFERENCES users(id)
);

-- RedemptionHistory Table
CREATE TABLE redemption_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    redeemed_amount DECIMAL(19, 2),
    redeemed_date TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
